### ISSUE TITLE
[Feature Request] manage testing models in a standard way

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#2103]
### Summary

Currently, we have many APIs to infer models, such as Python, C++, C, LAMMPS, etc. These APIs use minified models to test. Currently, all testing models are in the Python test directory `source/tests/infer/deepdipole_fake.pbtxt`. We hope we can move them out of that directory and manage them in a standard way.

### Detailed Description

For each model, we may create a metafile:

```yaml
model: deeppot
filename: some.pbtxt # relative to this file
type: pbtxt
results:
  - coords: [1., 2., 3., 4., 5., 6.]
    box: null
    atype: [0, 0]
    forces: [...]
```

I write YAML for convenience, but it could also be a JSON file. Each test program could read these files, and test results are not necessarily defined in the program.
